server:
  port: 8000

spring:
  application:
    name: roomly
  jpa:
    show-sql: true
    properties:
      hibernate:
        use_sql_comments: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 20
          batch_versioned_data: true
          fetch_size: 100
    hibernate:
      ddl-auto: validate
    open-in-view: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/roomly}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:123456}
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URI:http://localhost:8080/realms/roomly}
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

logging:
  level:
    org.springframework.security: DEBUG

storage:
  endpointUrl: https://${ENDPOINT_URI:hb.vkcloud-storage.ru}
  region: ${REGION_STORE:ru-msk}
  access_key: ${ACCESS_KEY}
  secret_key: ${SECRET_KEY}
  bucket_name: ${BUCKET_NAME:roomly}
  file_url_template: ${FILE_URL_TEMPLATE:https://roomly.hb.ru-msk.vkcloud-storage.ru/}
